Repository hazelcast/hive, pull requests merged in 2020-11, with the labels that each got.

#60 Fix the disabled button tooltip
  packages/ui/.loki/reference/chrome_fullHD_Components_Button_Primary_Disabled.png
  packages/ui/.loki/reference/chrome_fullHD_Components_Button_Primary_Disabled_Tooltip.png
  packages/ui/.loki/reference/chrome_fullHD_Components_Button_Primary_Focused.png
  packages/ui/.loki/reference/chrome_fullHD_Components_Button_Primary_Icon_Both_Focused.png
  packages/ui/.loki/reference/chrome_fullHD_Components_Button_Secondary_Disabled.png
  packages/ui/.loki/reference/chrome_fullHD_Components_Button_Secondary_Disabled_Tooltip.png
  packages/ui/.loki/reference/chrome_fullHD_Components_Button_Secondary_Focused.png
  packages/ui/.loki/reference/chrome_fullHD_Components_Button_Secondary_Icon_Both_Focused.png
  packages/ui/.loki/reference/chrome_fullHD_Components_Button_Transparent_Disabled.png
  packages/ui/.loki/reference/chrome_fullHD_Components_Button_Transparent_Focused.png
  packages/ui/.loki/reference/chrome_fullHD_Components_Button_Transparent_Icon_Both_Focused.png
  packages/ui/.loki/reference/chrome_laptop_Components_Button_Primary_Disabled.png
  packages/ui/.loki/reference/chrome_laptop_Components_Button_Primary_Disabled_Tooltip.png
  packages/ui/.loki/reference/chrome_laptop_Components_Button_Primary_Focused.png
  packages/ui/.loki/reference/chrome_laptop_Components_Button_Primary_Icon_Both_Focused.png
  packages/ui/.loki/reference/chrome_laptop_Components_Button_Secondary_Disabled.png
  packages/ui/.loki/reference/chrome_laptop_Components_Button_Secondary_Disabled_Tooltip.png
  packages/ui/.loki/reference/chrome_laptop_Components_Button_Secondary_Focused.png
  packages/ui/.loki/reference/chrome_laptop_Components_Button_Secondary_Icon_Both_Focused.png
  packages/ui/.loki/reference/chrome_laptop_Components_Button_Transparent_Disabled.png
  packages/ui/.loki/reference/chrome_laptop_Components_Button_Transparent_Focused.png
  packages/ui/.loki/reference/chrome_laptop_Components_Button_Transparent_Icon_Both_Focused.png
  packages/ui/.loki/reference/chrome_minimal_Components_Button_Primary_Disabled.png
  packages/ui/.loki/reference/chrome_minimal_Components_Button_Primary_Disabled_Tooltip.png
  packages/ui/.loki/reference/chrome_minimal_Components_Button_Primary_Focused.png
  packages/ui/.loki/reference/chrome_minimal_Components_Button_Primary_Icon_Both_Focused.png
  packages/ui/.loki/reference/chrome_minimal_Components_Button_Secondary_Disabled.png
  packages/ui/.loki/reference/chrome_minimal_Components_Button_Secondary_Disabled_Tooltip.png
  packages/ui/.loki/reference/chrome_minimal_Components_Button_Secondary_Focused.png
  packages/ui/.loki/reference/chrome_minimal_Components_Button_Secondary_Icon_Both_Focused.png
  packages/ui/.loki/reference/chrome_minimal_Components_Button_Transparent_Disabled.png
  packages/ui/.loki/reference/chrome_minimal_Components_Button_Transparent_Focused.png
  packages/ui/.loki/reference/chrome_minimal_Components_Button_Transparent_Icon_Both_Focused.png
  packages/ui/__stories__/Button.stories.tsx
  packages/ui/src/Alert.module.scss
  packages/ui/src/Alert.tsx
  packages/ui/src/Button.module.scss
  packages/ui/src/Button.tsx
Labels: UI, bug

#61 feat: badge component
  packages/ui/.loki/reference/chrome_fullHD_components_Badge_Critical_Normal.png
  packages/ui/.loki/reference/chrome_fullHD_components_Badge_Critical_Small.png
  packages/ui/.loki/reference/chrome_fullHD_components_Badge_Info_Normal.png
  packages/ui/.loki/reference/chrome_fullHD_components_Badge_Info_Small.png
  packages/ui/.loki/reference/chrome_fullHD_components_Badge_Long_Text.png
  packages/ui/.loki/reference/chrome_fullHD_components_Badge_Neutral_Normal.png
  packages/ui/.loki/reference/chrome_fullHD_components_Badge_Neutral_Small.png
  packages/ui/.loki/reference/chrome_fullHD_components_Badge_Success_Normal.png
  packages/ui/.loki/reference/chrome_fullHD_components_Badge_Success_Small.png
  packages/ui/.loki/reference/chrome_fullHD_components_Badge_Warning_Normal.png
  packages/ui/.loki/reference/chrome_fullHD_components_Badge_Warning_Small.png
  packages/ui/.loki/reference/chrome_fullHD_components_NumberBadge_Default.png
  packages/ui/.loki/reference/chrome_fullHD_components_NumberBadge_Less_Than_100.png
  packages/ui/.loki/reference/chrome_fullHD_components_NumberBadge_More_Than_99.png
  packages/ui/.loki/reference/chrome_laptop_components_Badge_Critical_Normal.png
  packages/ui/.loki/reference/chrome_laptop_components_Badge_Critical_Small.png
  packages/ui/.loki/reference/chrome_laptop_components_Badge_Info_Normal.png
  packages/ui/.loki/reference/chrome_laptop_components_Badge_Info_Small.png
  packages/ui/.loki/reference/chrome_laptop_components_Badge_Long_Text.png
  packages/ui/.loki/reference/chrome_laptop_components_Badge_Neutral_Normal.png
  packages/ui/.loki/reference/chrome_laptop_components_Badge_Neutral_Small.png
  packages/ui/.loki/reference/chrome_laptop_components_Badge_Success_Normal.png
  packages/ui/.loki/reference/chrome_laptop_components_Badge_Success_Small.png
  packages/ui/.loki/reference/chrome_laptop_components_Badge_Warning_Normal.png
  packages/ui/.loki/reference/chrome_laptop_components_Badge_Warning_Small.png
  packages/ui/.loki/reference/chrome_laptop_components_NumberBadge_Default.png
  packages/ui/.loki/reference/chrome_laptop_components_NumberBadge_Less_Than_100.png
  packages/ui/.loki/reference/chrome_laptop_components_NumberBadge_More_Than_99.png
  packages/ui/.loki/reference/chrome_minimal_components_Badge_Critical_Normal.png
  packages/ui/.loki/reference/chrome_minimal_components_Badge_Critical_Small.png
  packages/ui/.loki/reference/chrome_minimal_components_Badge_Info_Normal.png
  packages/ui/.loki/reference/chrome_minimal_components_Badge_Info_Small.png
  packages/ui/.loki/reference/chrome_minimal_components_Badge_Long_Text.png
  packages/ui/.loki/reference/chrome_minimal_components_Badge_Neutral_Normal.png
  packages/ui/.loki/reference/chrome_minimal_components_Badge_Neutral_Small.png
  packages/ui/.loki/reference/chrome_minimal_components_Badge_Success_Normal.png
  packages/ui/.loki/reference/chrome_minimal_components_Badge_Success_Small.png
  packages/ui/.loki/reference/chrome_minimal_components_Badge_Warning_Normal.png
  packages/ui/.loki/reference/chrome_minimal_components_Badge_Warning_Small.png
  packages/ui/.loki/reference/chrome_minimal_components_NumberBadge_Default.png
  packages/ui/.loki/reference/chrome_minimal_components_NumberBadge_Less_Than_100.png
  packages/ui/.loki/reference/chrome_minimal_components_NumberBadge_More_Than_99.png
  packages/ui/__stories__/Badge.stories.tsx
  packages/ui/__stories__/NumberBadge.stories.tsx
  packages/ui/__tests__/Badge.test.tsx
  packages/ui/__tests__/NumberBadge.test.tsx
  packages/ui/src/Badge.module.scss
  packages/ui/src/Badge.tsx
  packages/ui/src/NumberBadge.module.scss
  packages/ui/src/NumberBadge.tsx
  packages/ui/styles/constants/_sizes.scss
Labels: UI

#68 Fix Checkbox error margin
  packages/ui/.loki/reference/chrome_fullHD_Components_Checkbox_Indeterminate_With_Error.png
  packages/ui/.loki/reference/chrome_fullHD_Components_Checkbox_Two_Checkboxes.png
  packages/ui/.loki/reference/chrome_fullHD_Components_Checkbox_With_Error.png
  packages/ui/.loki/reference/chrome_laptop_Components_Checkbox_Indeterminate_With_Error.png
  packages/ui/.loki/reference/chrome_laptop_Components_Checkbox_Two_Checkboxes.png
  packages/ui/.loki/reference/chrome_laptop_Components_Checkbox_With_Error.png
  packages/ui/.loki/reference/chrome_minimal_Components_Checkbox_Indeterminate_With_Error.png
  packages/ui/.loki/reference/chrome_minimal_Components_Checkbox_Two_Checkboxes.png
  packages/ui/.loki/reference/chrome_minimal_Components_Checkbox_With_Error.png
  packages/ui/src/Checkbox.module.scss
  packages/ui/src/Checkbox.tsx
Labels: UI, bug

#67 feat(ui/icon): update aria properties
  packages/ui/src/Icon.tsx
Labels: UI, enhancement

#74 Upgrade react-resize-aware
  packages/ui/@types/react-resize-aware.d.ts
  packages/ui/package-lock.json
  packages/ui/package.json
  packages/ui/src/TextArea.tsx
  packages/ui/tsconfig.build.json
Labels: UI

#82 Fix empty string handling for the `NumberField`
  packages/ui/__tests__/NumberField.test.tsx
  packages/ui/src/NumberField.tsx
Labels: UI, bug

#83 Fix NumberField new value normalization
  packages/ui/.loki/reference/chrome_fullHD_Components_NumberField_Empty.png
  packages/ui/.loki/reference/chrome_laptop_Components_NumberField_Empty.png
  packages/ui/.loki/reference/chrome_minimal_Components_NumberField_Empty.png
  packages/ui/__stories__/NumberField.stories.tsx
  packages/ui/__tests__/NumberField.test.tsx
  packages/ui/src/NumberField.tsx
  packages/ui/src/NumberFieldFormik.tsx
Labels: UI, bug

#91 Fix accidental making of TextField and TextArea uncontrolled
  packages/ui/src/TextArea.tsx
  packages/ui/src/TextField.tsx
Labels: UI, bug

#93 Remove top-level margin
  packages/ui/src/Alert.tsx
  packages/ui/src/IconButton.module.scss
  packages/ui/src/Label.module.scss
  packages/ui/src/TextArea.module.scss
  packages/ui/src/TextField.module.scss
Labels: UI

#95 Use useIsomorphicLayoutEffect
  packages/ui/package-lock.json
  packages/ui/package.json
  packages/ui/src/NumberField.tsx
  packages/ui/src/TextArea.tsx
  packages/ui/src/TruncatedText.tsx
Labels: UI, bug

#100 fix(ui/checkbox): update label type
  packages/ui/.loki/reference/chrome_fullHD_Components_Checkbox_Label_With_Link.png
  packages/ui/.loki/reference/chrome_laptop_Components_Checkbox_Label_With_Link.png
  packages/ui/.loki/reference/chrome_minimal_Components_Checkbox_Label_With_Link.png
  packages/ui/__stories__/Checkbox.stories.tsx
  packages/ui/src/Checkbox.tsx
Labels: UI, bug

#102 Make button text centered
  packages/ui/.loki/reference/chrome_fullHD_Components_Button_Long.png
  packages/ui/.loki/reference/chrome_fullHD_Components_Button_Long_Centered.png
  packages/ui/.loki/reference/chrome_laptop_Components_Button_Long.png
  packages/ui/.loki/reference/chrome_laptop_Components_Button_Long_Centered.png
  packages/ui/.loki/reference/chrome_minimal_Components_Button_Long.png
  packages/ui/.loki/reference/chrome_minimal_Components_Button_Long_Centered.png
  packages/ui/__stories__/Button.stories.module.scss
  packages/ui/__stories__/Button.stories.tsx
  packages/ui/src/Button.module.scss
  packages/ui/styles/constants/_sizes.scss
Labels: UI
