Repository hazelcast/hive, pull requests merged in 2020-12, with the labels that each got.

#104 IE11 works with layout effect
  packages/ui/src/NumberField.tsx
  packages/ui/src/TextArea.tsx
  packages/ui/src/TruncatedText.tsx
Labels: UI, bug

#106 fix(ui): add missing select exports
  packages/ui/src/index.ts
Labels: bug

#109 Fix SelectField rendering in SSR env
  packages/ui/src/SelectField.tsx
  packages/ui/src/utils/ssr.ts
Labels: UI, bug

#114 Extend Link API to support NextJS integration
  packages/ui/__tests__/Link.test.tsx
  packages/ui/package-lock.json
  packages/ui/package.json
  packages/ui/src/Alert.tsx
  packages/ui/src/Link.tsx
Labels: UI

#115 Unify formik custom onChange
  packages/ui/src/NumberFieldFormik.tsx
  packages/ui/src/SelectFieldFormik.tsx
  packages/ui/src/utils/formik.ts
Labels: UI

#112 feat(ui/textfield): add email type option
  packages/ui/.loki/reference/chrome_fullHD_Components_TextField_Type_Email.png
  packages/ui/.loki/reference/chrome_fullHD_Components_TextField_Type_Number.png
  packages/ui/.loki/reference/chrome_fullHD_Components_TextField_Type_Password.png
  packages/ui/.loki/reference/chrome_fullHD_Components_TextField_Type_Search.png
  packages/ui/.loki/reference/chrome_fullHD_Components_TextField_Type_Tel.png
  packages/ui/.loki/reference/chrome_fullHD_Components_TextField_Type_Text.png
  packages/ui/.loki/reference/chrome_fullHD_Components_TextField_Type_URL.png
  packages/ui/.loki/reference/chrome_laptop_Components_TextField_Type_Email.png
  packages/ui/.loki/reference/chrome_laptop_Components_TextField_Type_Number.png
  packages/ui/.loki/reference/chrome_laptop_Components_TextField_Type_Password.png
  packages/ui/.loki/reference/chrome_laptop_Components_TextField_Type_Search.png
  packages/ui/.loki/reference/chrome_laptop_Components_TextField_Type_Tel.png
  packages/ui/.loki/reference/chrome_laptop_Components_TextField_Type_Text.png
  packages/ui/.loki/reference/chrome_laptop_Components_TextField_Type_URL.png
  packages/ui/.loki/reference/chrome_minimal_Components_TextField_Type_Email.png
  packages/ui/.loki/reference/chrome_minimal_Components_TextField_Type_Number.png
  packages/ui/.loki/reference/chrome_minimal_Components_TextField_Type_Password.png
  packages/ui/.loki/reference/chrome_minimal_Components_TextField_Type_Search.png
  packages/ui/.loki/reference/chrome_minimal_Components_TextField_Type_Tel.png
  packages/ui/.loki/reference/chrome_minimal_Components_TextField_Type_Text.png
  packages/ui/.loki/reference/chrome_minimal_Components_TextField_Type_URL.png
  packages/ui/__stories__/TextField.stories.tsx
  packages/ui/src/TextField.tsx
Labels: UI, enhancement

#116 Add uuid support to SSR
  README.md
  packages/ui/__stories__/Radio.stories.tsx
  packages/ui/__stories__/RadioGroup.stories.tsx
  packages/ui/__tests__/Checkbox.test.tsx
  packages/ui/__tests__/Radio.test.tsx
  packages/ui/__tests__/SelectField.test.tsx
  packages/ui/__tests__/TextArea.test.tsx
  packages/ui/__tests__/TextField.test.tsx
  packages/ui/package-lock.json
  packages/ui/package.json
  packages/ui/src/Button.tsx
  packages/ui/src/Checkbox.tsx
  packages/ui/src/Radio.tsx
  packages/ui/src/RadioGroup.tsx
  packages/ui/src/SelectField.tsx
  packages/ui/src/TextArea.tsx
  packages/ui/src/TextField.tsx
  packages/ui/src/TruncatedText.tsx
Labels: UI, bug

#117 Fix Chrome autofill
  packages/ui/.loki/reference/chrome_fullHD_Components_PasswordField_Autofill.png
  packages/ui/.loki/reference/chrome_fullHD_Components_TextField_With_Icon_Autofill.png
  packages/ui/.loki/reference/chrome_laptop_Components_PasswordField_Autofill.png
  packages/ui/.loki/reference/chrome_laptop_Components_TextField_With_Icon_Autofill.png
  packages/ui/.loki/reference/chrome_minimal_Components_PasswordField_Autofill.png
  packages/ui/.loki/reference/chrome_minimal_Components_TextField_With_Icon_Autofill.png
  packages/ui/__stories__/PasswordField.stories.tsx
  packages/ui/__stories__/TextField.stories.tsx
  packages/ui/src/TextField.module.scss
  packages/ui/styles/helpers/_index.scss
  packages/ui/styles/helpers/_input.scss
Labels: UI, bug

#122 Wrap all radio stories in form
  packages/ui/__stories__/Checkbox.stories.tsx
  packages/ui/__stories__/Radio.stories.tsx
  packages/ui/__stories__/RadioGroup.stories.tsx
  packages/ui/__stories__/decorators.tsx
Labels: bug

#119 Card component
  packages/ui/.loki/reference/chrome_fullHD_Components_Card_Card_Simple.png
  packages/ui/.loki/reference/chrome_fullHD_Components_Card_Card_With_Icon.png
  packages/ui/.loki/reference/chrome_fullHD_Components_Card_Card_With_Icon_And_Separator.png
  packages/ui/.loki/reference/chrome_fullHD_Components_Card_Card_With_Separator.png
  packages/ui/.loki/reference/chrome_fullHD_Components_Card_Card_With_Small_Text.png
  packages/ui/.loki/reference/chrome_laptop_Components_Card_Card_Simple.png
  packages/ui/.loki/reference/chrome_laptop_Components_Card_Card_With_Icon.png
  packages/ui/.loki/reference/chrome_laptop_Components_Card_Card_With_Icon_And_Separator.png
  packages/ui/.loki/reference/chrome_laptop_Components_Card_Card_With_Separator.png
  packages/ui/.loki/reference/chrome_laptop_Components_Card_Card_With_Small_Text.png
  packages/ui/.loki/reference/chrome_minimal_Components_Card_Card_Simple.png
  packages/ui/.loki/reference/chrome_minimal_Components_Card_Card_With_Icon.png
  packages/ui/.loki/reference/chrome_minimal_Components_Card_Card_With_Icon_And_Separator.png
  packages/ui/.loki/reference/chrome_minimal_Components_Card_Card_With_Separator.png
  packages/ui/.loki/reference/chrome_minimal_Components_Card_Card_With_Small_Text.png
  packages/ui/__stories__/Card.stories.tsx
  packages/ui/__stories__/utils.scss
  packages/ui/__tests__/Card.test.tsx
  packages/ui/src/Card.module.scss
  packages/ui/src/Card.tsx
  packages/ui/src/index.ts
Labels: enhancement

#131 Add default button type
  packages/ui/__tests__/Button.test.tsx
  packages/ui/src/Button.tsx
  packages/ui/src/IconButton.tsx
Labels: UI

#137 feat(ui/icon): add support for simple-icons
  .gitignore
  packages/ui/.loki/reference/chrome_fullHD_Components_Icon_Feather_Icon_Normal.png
  packages/ui/.loki/reference/chrome_fullHD_Components_Icon_Feather_Icon_Normal_Custom_Colour.png
  packages/ui/.loki/reference/chrome_fullHD_Components_Icon_Feather_Icon_Small.png
  packages/ui/.loki/reference/chrome_fullHD_Components_Icon_Feather_Icon_Small_Custom_Colour.png
  packages/ui/.loki/reference/chrome_fullHD_Components_Icon_Simple_Icon_Normal.png
  packages/ui/.loki/reference/chrome_fullHD_Components_Icon_Simple_Icon_Normal_Custom_Colour.png
  packages/ui/.loki/reference/chrome_fullHD_Components_Icon_Simple_Icon_Small.png
  packages/ui/.loki/reference/chrome_fullHD_Components_Icon_Simple_Icon_Small_Custom_Colour.png
  packages/ui/.loki/reference/chrome_laptop_Components_Icon_Feather_Icon_Normal.png
  packages/ui/.loki/reference/chrome_laptop_Components_Icon_Feather_Icon_Normal_Custom_Colour.png
  packages/ui/.loki/reference/chrome_laptop_Components_Icon_Feather_Icon_Small.png
  packages/ui/.loki/reference/chrome_laptop_Components_Icon_Feather_Icon_Small_Custom_Colour.png
  packages/ui/.loki/reference/chrome_laptop_Components_Icon_Simple_Icon_Normal.png
  packages/ui/.loki/reference/chrome_laptop_Components_Icon_Simple_Icon_Normal_Custom_Colour.png
  packages/ui/.loki/reference/chrome_laptop_Components_Icon_Simple_Icon_Small.png
  packages/ui/.loki/reference/chrome_laptop_Components_Icon_Simple_Icon_Small_Custom_Colour.png
  packages/ui/.loki/reference/chrome_minimal_Components_Icon_Feather_Icon_Normal.png
  packages/ui/.loki/reference/chrome_minimal_Components_Icon_Feather_Icon_Normal_Custom_Colour.png
  packages/ui/.loki/reference/chrome_minimal_Components_Icon_Feather_Icon_Small.png
  packages/ui/.loki/reference/chrome_minimal_Components_Icon_Feather_Icon_Small_Custom_Colour.png
  packages/ui/.loki/reference/chrome_minimal_Components_Icon_Simple_Icon_Normal.png
  packages/ui/.loki/reference/chrome_minimal_Components_Icon_Simple_Icon_Normal_Custom_Colour.png
  packages/ui/.loki/reference/chrome_minimal_Components_Icon_Simple_Icon_Small.png
  packages/ui/.loki/reference/chrome_minimal_Components_Icon_Simple_Icon_Small_Custom_Colour.png
  packages/ui/__stories__/Icon.stories.tsx
  packages/ui/package-lock.json
  packages/ui/package.json
  packages/ui/src/Icon.tsx
Labels: UI, enhancement

#140 fix(ui/alert): optional "closeToast" prop
  packages/ui/.loki/reference/chrome_fullHD_components_Alert_Critical_Without_Close_Button.png
  packages/ui/.loki/reference/chrome_fullHD_components_Alert_Info_Without_Close_Button.png
  packages/ui/.loki/reference/chrome_fullHD_components_Alert_Success_Without_Close_Button.png
  packages/ui/.loki/reference/chrome_fullHD_components_Alert_Warning_Without_Close_Button.png
  packages/ui/.loki/reference/chrome_laptop_components_Alert_Critical_Without_Close_Button.png
  packages/ui/.loki/reference/chrome_laptop_components_Alert_Info_Without_Close_Button.png
  packages/ui/.loki/reference/chrome_laptop_components_Alert_Success_Without_Close_Button.png
  packages/ui/.loki/reference/chrome_laptop_components_Alert_Warning_Without_Close_Button.png
  packages/ui/.loki/reference/chrome_minimal_components_Alert_Critical_Without_Close_Button.png
  packages/ui/.loki/reference/chrome_minimal_components_Alert_Info_Without_Close_Button.png
  packages/ui/.loki/reference/chrome_minimal_components_Alert_Success_Without_Close_Button.png
  packages/ui/.loki/reference/chrome_minimal_components_Alert_Warning_Without_Close_Button.png
  packages/ui/__stories__/Alert.stories.tsx
  packages/ui/src/Alert.tsx
Labels: UI, bug

#138 fix(ui/textfield): formik version type options
  packages/ui/src/NumberField.tsx
  packages/ui/src/TextField.tsx
  packages/ui/src/TextFieldFormik.tsx
Labels: UI, bug

#139 fix(ui/passwordfield): input icon
  packages/ui/.loki/reference/chrome_fullHD_Components_PasswordField_With_Icon.png
  packages/ui/.loki/reference/chrome_laptop_Components_PasswordField_With_Icon.png
  packages/ui/.loki/reference/chrome_minimal_Components_PasswordField_With_Icon.png
  packages/ui/__stories__/PasswordField.stories.tsx
  packages/ui/src/PasswordField.tsx
Labels: UI, bug

#142 Add license
  LICENSE
  packages/helpers/package.json
  packages/services/package.json
  packages/test-helpers/package.json
  packages/ui/package.json
Labels: infrastructure
