Repository hazelcast/hive, pull requests merged in 2020-10, with the labels that each got.

#53 Fix Help vertical centering
  packages/ui/.loki/reference/chrome_fullHD_Components_Help_Text_With_Help.png
  packages/ui/.loki/reference/chrome_fullHD_Components_Help_Text_With_Help_No_Padding.png
  packages/ui/.loki/reference/chrome_fullHD_Components_TextField_With_Helper_Text.png
  packages/ui/.loki/reference/chrome_fullHD_Components_TextField_With_Icon_With_Helper_Text.png
  packages/ui/.loki/reference/chrome_laptop_Components_Help_Text_With_Help.png
  packages/ui/.loki/reference/chrome_laptop_Components_Help_Text_With_Help_No_Padding.png
  packages/ui/.loki/reference/chrome_laptop_Components_TextField_With_Helper_Text.png
  packages/ui/.loki/reference/chrome_laptop_Components_TextField_With_Icon_With_Helper_Text.png
  packages/ui/.loki/reference/chrome_minimal_Components_Help_Text_With_Help.png
  packages/ui/.loki/reference/chrome_minimal_Components_Help_Text_With_Help_No_Padding.png
  packages/ui/.loki/reference/chrome_minimal_Components_TextField_With_Helper_Text.png
  packages/ui/.loki/reference/chrome_minimal_Components_TextField_With_Icon_With_Helper_Text.png
  packages/ui/src/Help.module.scss
Labels: UI, bug

#55 Add `verify-all` command
  README.md
  package.json
Labels: infrastructure

#56 feat: add button disabled tooltip
  packages/ui/__stories__/Button.stories.tsx
  packages/ui/__tests__/Button.test.tsx
  packages/ui/src/Button.tsx
Labels: UI, enhancement

#57 fix: deprecate usage of mount()
  packages/ui/__tests__/Alert.test.tsx
  packages/ui/__tests__/Button.test.tsx
  packages/ui/__tests__/Toast.test.tsx
Labels: enhancement
