Repository hazelcast/hive, pull requests merged in 2021-01, with the labels that each got.

#146 feat: toast icon shrinking
  packages/ui/.loki/reference/chrome_fullHD_components_Toast_Long_Text.png
  packages/ui/.loki/reference/chrome_fullHD_components_Toast_Long_Word.png
  packages/ui/.loki/reference/chrome_laptop_components_Toast_Long_Text.png
  packages/ui/.loki/reference/chrome_laptop_components_Toast_Long_Word.png
  packages/ui/.loki/reference/chrome_minimal_components_Toast_Long_Text.png
  packages/ui/.loki/reference/chrome_minimal_components_Toast_Long_Word.png
  packages/ui/src/Toast.module.scss
Labels: bug

#150 [Core UI] Loader
  packages/ui/.loki/reference/chrome_fullHD_Components_Button_Primary_Icon_Both_Loading.png
  packages/ui/.loki/reference/chrome_fullHD_Components_Button_Primary_Loading.png
  packages/ui/.loki/reference/chrome_fullHD_Components_Button_Secondary_Icon_Both_Loading.png
  packages/ui/.loki/reference/chrome_fullHD_Components_Button_Secondary_Loading.png
  packages/ui/.loki/reference/chrome_fullHD_Components_Button_Transparent_Icon_Both_Loading.png
  packages/ui/.loki/reference/chrome_fullHD_Components_Button_Transparent_Loading.png
  packages/ui/.loki/reference/chrome_fullHD_Components_Loader_Contrast_Normal.png
  packages/ui/.loki/reference/chrome_fullHD_Components_Loader_Contrast_Small.png
  packages/ui/.loki/reference/chrome_fullHD_Components_Loader_Contrast_X_Large.png
  packages/ui/.loki/reference/chrome_fullHD_Components_Loader_Inherit_Normal.png
  packages/ui/.loki/reference/chrome_fullHD_Components_Loader_Inherit_Small.png
  packages/ui/.loki/reference/chrome_fullHD_Components_Loader_Inherit_X_Large.png
  packages/ui/.loki/reference/chrome_fullHD_Components_Loader_Primary_Normal.png
  packages/ui/.loki/reference/chrome_fullHD_Components_Loader_Primary_Small.png
  packages/ui/.loki/reference/chrome_fullHD_Components_Loader_Primary_X_Large.png
  packages/ui/.loki/reference/chrome_laptop_Components_Button_Primary_Icon_Both_Loading.png
  packages/ui/.loki/reference/chrome_laptop_Components_Button_Primary_Loading.png
  packages/ui/.loki/reference/chrome_laptop_Components_Button_Secondary_Icon_Both_Loading.png
  packages/ui/.loki/reference/chrome_laptop_Components_Button_Secondary_Loading.png
  packages/ui/.loki/reference/chrome_laptop_Components_Button_Transparent_Icon_Both_Loading.png
  packages/ui/.loki/reference/chrome_laptop_Components_Button_Transparent_Loading.png
  packages/ui/.loki/reference/chrome_laptop_Components_Loader_Contrast_Normal.png
  packages/ui/.loki/reference/chrome_laptop_Components_Loader_Contrast_Small.png
  packages/ui/.loki/reference/chrome_laptop_Components_Loader_Contrast_X_Large.png
  packages/ui/.loki/reference/chrome_laptop_Components_Loader_Inherit_Normal.png
  packages/ui/.loki/reference/chrome_laptop_Components_Loader_Inherit_Small.png
  packages/ui/.loki/reference/chrome_laptop_Components_Loader_Inherit_X_Large.png
  packages/ui/.loki/reference/chrome_laptop_Components_Loader_Primary_Normal.png
  packages/ui/.loki/reference/chrome_laptop_Components_Loader_Primary_Small.png
  packages/ui/.loki/reference/chrome_laptop_Components_Loader_Primary_X_Large.png
  packages/ui/.loki/reference/chrome_minimal_Components_Button_Primary_Icon_Both_Loading.png
  packages/ui/.loki/reference/chrome_minimal_Components_Button_Primary_Loading.png
  packages/ui/.loki/reference/chrome_minimal_Components_Button_Secondary_Icon_Both_Loading.png
  packages/ui/.loki/reference/chrome_minimal_Components_Button_Secondary_Loading.png
  packages/ui/.loki/reference/chrome_minimal_Components_Button_Transparent_Icon_Both_Loading.png
  packages/ui/.loki/reference/chrome_minimal_Components_Button_Transparent_Loading.png
  packages/ui/.loki/reference/chrome_minimal_Components_Loader_Contrast_Normal.png
  packages/ui/.loki/reference/chrome_minimal_Components_Loader_Contrast_Small.png
  packages/ui/.loki/reference/chrome_minimal_Components_Loader_Contrast_X_Large.png
  packages/ui/.loki/reference/chrome_minimal_Components_Loader_Inherit_Normal.png
  packages/ui/.loki/reference/chrome_minimal_Components_Loader_Inherit_Small.png
  packages/ui/.loki/reference/chrome_minimal_Components_Loader_Inherit_X_Large.png
  packages/ui/.loki/reference/chrome_minimal_Components_Loader_Primary_Normal.png
  packages/ui/.loki/reference/chrome_minimal_Components_Loader_Primary_Small.png
  packages/ui/.loki/reference/chrome_minimal_Components_Loader_Primary_X_Large.png
  packages/ui/__stories__/Button.stories.tsx
  packages/ui/__stories__/Loader.stories.tsx
  packages/ui/__tests__/Button.test.tsx
  packages/ui/src/Button.tsx
  packages/ui/src/Icon.tsx
  packages/ui/src/Loader.module.scss
  packages/ui/src/Loader.tsx
  packages/ui/src/index.ts
  packages/ui/stylelint.config.js
  packages/ui/styles/constants/_animations.scss
  packages/ui/styles/constants/_sizes.scss
Labels: UI

#155 Fix `validate` typings
  packages/ui/src/SelectFieldFormik.tsx
  packages/ui/src/TextFieldFormik.tsx
Labels: bug

#158 Fix typography and work-break
  packages/ui/src/Toast.module.scss
Labels: UI, bug

#161 Fix missing exports and Dialog minor bugs
  packages/ui/.loki/reference/chrome_minimal_Components_Dialog_Default.png
  packages/ui/.loki/reference/chrome_minimal_Components_Dialog_Long.png
  packages/ui/.loki/reference/chrome_minimal_Components_Dialog_With_Action.png
  packages/ui/.loki/reference/chrome_minimal_Components_Dialog_With_Action_Disabled.png
  packages/ui/.loki/reference/chrome_minimal_Components_Dialog_With_Danger_Action.png
  packages/ui/.loki/reference/chrome_minimal_Components_Dialog_With_Danger_Action_Disabled.png
  packages/ui/.loki/reference/chrome_minimal_Components_Modal_Default.png
  packages/ui/.loki/reference/chrome_minimal_Components_Modal_Not_Closable.png
  packages/ui/.loki/reference/chrome_minimal_Components_Modal_With_Action.png
  packages/ui/.loki/reference/chrome_minimal_Components_Modal_With_Action_Disabled.png
  packages/ui/.loki/reference/chrome_minimal_Components_Modal_With_Danger_Action.png
  packages/ui/.loki/reference/chrome_minimal_Components_Modal_With_Danger_Action_Disabled.png
  packages/ui/.loki/reference/chrome_minimal_Components_Modal_With_Icon.png
  packages/ui/.loki/reference/chrome_minimal_Components_Modal_With_Long_Title.png
  packages/ui/.loki/reference/chrome_minimal_Components_Modal_With_Multiple_Actions.png
  packages/ui/__stories__/Dialog.stories.tsx
  packages/ui/__stories__/Modal.stories.tsx
  packages/ui/__tests__/Dialog.test.tsx
  packages/ui/src/Dialog.module.scss
  packages/ui/src/Dialog.tsx
  packages/ui/src/Modal.module.scss
  packages/ui/src/Notification.tsx
  packages/ui/src/index.ts
Labels: bug

#162 Fix Modal pointer events
  packages/ui/src/Modal.module.scss
Labels: bug

#168 Fix TextField styles
  packages/ui/.loki/reference/chrome_minimal_Components_TextField_Disabled_With_Hover.png
  packages/ui/.loki/reference/chrome_minimal_Components_TextField_Focused_With_Hover.png
  packages/ui/__stories__/NumberField.stories.tsx
  packages/ui/__stories__/PasswordField.stories.tsx
  packages/ui/__stories__/TextField.stories.tsx
  packages/ui/__tests__/NumberField.test.tsx
  packages/ui/__tests__/PasswordField.test.tsx
  packages/ui/src/NumberField.tsx
  packages/ui/src/PasswordField.tsx
  packages/ui/src/TextField.module.scss
  packages/ui/src/TextField.tsx
Labels: bug

#170 Pass properties to Link in Alert component
  packages/ui/__tests__/Alert.test.tsx
  packages/ui/src/Alert.tsx
Labels: bug

#173 fix: icon/iconbutton outline spacing
  packages/ui/.loki/reference/chrome_minimal_components_Badge_Long_Text.png
  packages/ui/src/Icon.module.scss
  packages/ui/src/Icon.tsx
  packages/ui/src/TextField.module.scss
  packages/ui/src/TextField.tsx
Labels: bug

#159 feat(PasswordFieldn): add support for "id" prop
  packages/ui/src/PasswordField.tsx
  packages/ui/src/TextField.tsx
Labels: UI

#171 Feat/tabs
  packages/test-helpers/src/hooks.tsx
  packages/ui/.loki/reference/chrome_minimal_Components_Tabs_Controlled.png
  packages/ui/.loki/reference/chrome_minimal_Components_Tabs_Default.png
  packages/ui/.loki/reference/chrome_minimal_Components_Tabs_Full_Width.png
  packages/ui/__stories__/Tabs.stories.tsx
  packages/ui/__tests__/Tabs/Tab.test.tsx
  packages/ui/__tests__/Tabs/TabContext.test.tsx
  packages/ui/__tests__/Tabs/TabList.test.tsx
  packages/ui/__tests__/Tabs/TabPanel.test.tsx
  packages/ui/setupTests.ts
  packages/ui/src/Button.tsx
  packages/ui/src/Tabs/Tab.module.scss
  packages/ui/src/Tabs/Tab.tsx
  packages/ui/src/Tabs/TabContext.tsx
  packages/ui/src/Tabs/TabList.module.scss
  packages/ui/src/Tabs/TabList.tsx
  packages/ui/src/Tabs/TabPanel.module.scss
  packages/ui/src/Tabs/TabPanel.tsx
  packages/ui/src/Tabs/index.ts
  packages/ui/src/index.ts
  packages/ui/src/utils/keyboard.ts
Labels: UI
