Repository hazelcast/hive, pull requests merged in 2021-03, with the labels that each got.

#191 [Core-UI ] circular progress bar
  packages/ui/.loki/reference/chrome_minimal_Components_CircularProgressBar_Default.png
  packages/ui/.loki/reference/chrome_minimal_Components_CircularProgressBar_Memory_Usage_Example.png
  packages/ui/.loki/reference/chrome_minimal_Components_Slider_Slider_With_Max_Over_100.png
  packages/ui/__stories__/CircularProgressBar.stories.module.scss
  packages/ui/__stories__/CircularProgressBar.stories.tsx
  packages/ui/__stories__/Slider.stories.tsx
  packages/ui/__tests__/CircularProgressBar.test.tsx
  packages/ui/src/CircularProgressBar.module.scss
  packages/ui/src/CircularProgressBar.tsx
  packages/ui/src/Slider.tsx
  packages/ui/src/index.ts
Labels: UI

#181 Feature/date time picker
  package-lock.json
  packages/test-helpers/src/time.ts
  packages/ui/.loki/reference/chrome_minimal_Components_Button_Secondary_Disabled_Tooltip.png
  packages/ui/.loki/reference/chrome_minimal_Components_CalendarRange_Default.png
  packages/ui/.loki/reference/chrome_minimal_Components_CalendarRange_End_Open.png
  packages/ui/.loki/reference/chrome_minimal_Components_CalendarRange_Start_Open.png
  packages/ui/.loki/reference/chrome_minimal_Components_CalendarRange_With_Time_Inputs.png
  packages/ui/.loki/reference/chrome_minimal_Components_Calendar_Default.png
  packages/ui/.loki/reference/chrome_minimal_Components_Calendar_Disabled.png
  packages/ui/.loki/reference/chrome_minimal_Components_Calendar_Open.png
  packages/ui/.loki/reference/chrome_minimal_Components_Calendar_With_Time.png
  packages/ui/.loki/reference/chrome_minimal_Components_TextField_With_Trailing_Icon.png
  packages/ui/.loki/reference/chrome_minimal_Components_TextField_With_Trailing_Icon_Disabled.png
  packages/ui/.loki/reference/chrome_minimal_Components_TimeField_Default.png
  packages/ui/.loki/reference/chrome_minimal_Components_TimeField_Disabled.png
  packages/ui/.loki/reference/chrome_minimal_Components_TimeField_Error.png
  packages/ui/.loki/reference/chrome_minimal_Components_TimeField_Focused.png
  packages/ui/.loki/reference/chrome_minimal_Components_TimeField_Focused_With_Error.png
  packages/ui/.loki/reference/chrome_minimal_Components_TimeField_Focused_With_Hover.png
  packages/ui/.loki/reference/chrome_minimal_Components_TimeField_Hovered.png
  packages/ui/.loki/reference/chrome_minimal_Components_TimeField_Time_Field_Wrapped_In_Formik.png
  packages/ui/.loki/reference/chrome_minimal_Components_TimeField_With_Seconds.png
  packages/ui/.loki/reference/chrome_minimal_Components_Tooltip_Left_End_Placement.png
  packages/ui/.loki/reference/chrome_minimal_Components_Tooltip_Left_Placement.png
  packages/ui/.loki/reference/chrome_minimal_Components_Tooltip_Left_Start_Placement.png
  packages/ui/.storybook/theme.js
  packages/ui/__stories__/Calendar.stories.tsx
  packages/ui/__stories__/CalendarRange.stories.tsx
  packages/ui/__stories__/TextField.stories.tsx
  packages/ui/__stories__/TimeField.stories.tsx
  packages/ui/__stories__/utils.scss
  packages/ui/__tests__/Calendar/Calendar.test.tsx
  packages/ui/__tests__/Calendar/CalendarRange.test.tsx
  packages/ui/__tests__/Calendar/components/CalendarHeader.test.tsx
  packages/ui/__tests__/Calendar/components/CalendarInput.test.tsx
  packages/ui/__tests__/Calendar/components/CalendarTime.test.tsx
  packages/ui/__tests__/TextField.test.tsx
  packages/ui/__tests__/TimeField.test.tsx
  packages/ui/__tests__/TimeFieldFormik.test.tsx
  packages/ui/package-lock.json
  packages/ui/package.json
  packages/ui/src/Calendar/Calendar.module.scss
  packages/ui/src/Calendar/Calendar.tsx
  packages/ui/src/Calendar/CalendarRange.module.scss
  packages/ui/src/Calendar/CalendarRange.tsx
  packages/ui/src/Calendar/components/CalendarHeader.tsx
  packages/ui/src/Calendar/components/CalendarInput.tsx
  packages/ui/src/Calendar/components/CalendarTime.module.scss
  packages/ui/src/Calendar/components/CalendarTime.tsx
  packages/ui/src/Calendar/helpers/consts.ts
  packages/ui/src/IconButton.tsx
  packages/ui/src/TextField.module.scss
  packages/ui/src/TextField.tsx
  packages/ui/src/TimeField.module.scss
  packages/ui/src/TimeField.tsx
  packages/ui/src/TimeFieldFormik.tsx
  packages/ui/styles/constants/_colors.scss
  packages/ui/styles/constants/_sizes.scss
  packages/ui/styles/constants/_typography.scss
  packages/ui/styles/helpers/_a11y.scss
Labels: enhancement

#194 Add missing Calendar exports
  packages/ui/src/index.ts
Labels: bug

#195 Feat: Overlay
  packages/ui/.loki/reference/chrome_minimal_Components_Overlay_Default.png
  packages/ui/.loki/reference/chrome_minimal_Components_Overlay_Open.png
  packages/ui/__stories__/Overlay.stories.module.scss
  packages/ui/__stories__/Overlay.stories.tsx
  packages/ui/__tests__/Overlay.test.tsx
  packages/ui/src/Link.tsx
  packages/ui/src/Overlay.module.scss
  packages/ui/src/Overlay.tsx
  packages/ui/src/index.ts
  packages/ui/styles/constants/_colors.scss
  packages/ui/styles/constants/_sizes.scss
Labels: UI

#196 Add ref forwarding for Icon
  packages/ui/src/Icon.tsx
Labels: enhancement

#197 Feature/add titleless card
  packages/ui/.loki/reference/chrome_minimal_Components_Card_Without_Title.png
  packages/ui/__stories__/Card.stories.tsx
  packages/ui/src/Card.module.scss
  packages/ui/src/Card.tsx
Labels: enhancement

#198 Add missing "large" icon size implementation
  packages/ui/.loki/reference/chrome_minimal_Components_Loader_Contrast_Large.png
  packages/ui/.loki/reference/chrome_minimal_Components_Loader_Inherit_Large.png
  packages/ui/.loki/reference/chrome_minimal_Components_Loader_Primary_Large.png
  packages/ui/.loki/reference/chrome_minimal_components_EmptyState_Horizontal.png
  packages/ui/.loki/reference/chrome_minimal_components_EmptyState_Horizontal_With_Action.png
  packages/ui/.loki/reference/chrome_minimal_components_EmptyState_Horizontal_With_Description.png
  packages/ui/.loki/reference/chrome_minimal_components_EmptyState_Horizontal_With_Description_And_Action.png
  packages/ui/.loki/reference/chrome_minimal_components_EmptyState_Horizontal_With_Description_And_Action_Long.png
  packages/ui/.loki/reference/chrome_minimal_components_EmptyState_Vertical.png
  packages/ui/.loki/reference/chrome_minimal_components_EmptyState_Vertical_Description_And_Action.png
  packages/ui/.loki/reference/chrome_minimal_components_EmptyState_Vertical_With_Action.png
  packages/ui/.loki/reference/chrome_minimal_components_EmptyState_Vertical_With_Description.png
  packages/ui/.loki/reference/chrome_minimal_components_EmptyState_Vertical_With_Description_And_Action_Long.png
  packages/ui/__stories__/Loader.stories.tsx
  packages/ui/src/Icon.module.scss
  packages/ui/src/Loader.module.scss
  packages/ui/src/Loader.tsx
Labels: bug

#200 Add IconButton padding to match input height
  packages/ui/.loki/reference/chrome_minimal_Components_IconButton_Primary_Padding_Normal.png
  packages/ui/__stories__/IconButton.stories.tsx
  packages/ui/src/IconButton.module.scss
  packages/ui/src/IconButton.tsx
Labels: enhancement

#202 Add customizable sizes for Help
  packages/ui/.loki/reference/chrome_minimal_Components_Help_Help_Large.png
  packages/ui/.loki/reference/chrome_minimal_Components_Help_Help_Normal.png
  packages/ui/.loki/reference/chrome_minimal_Components_Help_Help_Small.png
  packages/ui/.loki/reference/chrome_minimal_Components_Help_Help_X_Large.png
  packages/ui/__stories__/Help.stories.tsx
  packages/ui/src/Help.tsx
Labels: enhancement

#199 Move margin to field label
  packages/ui/.loki/reference/chrome_minimal_Components_NumberField_With_Helper_Text.png
  packages/ui/.loki/reference/chrome_minimal_Components_Pagination_Default.png
  packages/ui/.loki/reference/chrome_minimal_Components_Pagination_Full.png
  packages/ui/.loki/reference/chrome_minimal_Components_PasswordField_With_Helper_Text.png
  packages/ui/.loki/reference/chrome_minimal_Components_SelectField_With_Helper_Text.png
  packages/ui/.loki/reference/chrome_minimal_Components_Table_Controlled_Pagination.png
  packages/ui/.loki/reference/chrome_minimal_Components_Table_Uncontrolled_Pagination.png
  packages/ui/.loki/reference/chrome_minimal_Components_TextField_With_Helper_Text.png
  packages/ui/.loki/reference/chrome_minimal_Components_TextField_With_Icon_With_Helper_Text.png
  packages/ui/__tests__/SelectField.test.tsx
  packages/ui/__tests__/TextField.test.tsx
  packages/ui/src/SelectField.module.scss
  packages/ui/src/SelectField.tsx
  packages/ui/src/TextArea.module.scss
  packages/ui/src/TextArea.tsx
  packages/ui/src/TextField.module.scss
  packages/ui/src/TextField.tsx
  setupTests.base.ts
Labels: enhancement

#209 feat: add bodySmaller and bodyTiny font sizes
  packages/ui/styles/constants/_typography.scss
Labels: enhancement

#213 Fix Card children type
  packages/ui/src/Card.tsx
Labels: bug

#223 Fix: make helperText props dependent on Help props
  packages/ui/src/Checkbox.tsx
  packages/ui/src/NumberField.tsx
  packages/ui/src/PasswordField.tsx
  packages/ui/src/Radio.tsx
  packages/ui/src/SelectField.tsx
  packages/ui/src/TextArea.tsx
  packages/ui/src/TextField.tsx
  packages/ui/src/Toggle.tsx
Labels: enhancement

#222 feat: add nav icons
  packages/icons/.loki/reference/chrome_minimal_Icons_Icons.png
  packages/icons/src/Compute.tsx
  packages/icons/src/Folder.tsx
  packages/icons/src/Streaming.tsx
  packages/icons/src/index.tsx
Labels: enhancement

#224 feat: add inset outline option
  package-lock.json
  packages/ui/.loki/reference/chrome_minimal_Components_Button_Outline_Inset.png
  packages/ui/__stories__/Button.stories.tsx
  packages/ui/__tests__/Button.test.tsx
  packages/ui/src/Button.module.scss
  packages/ui/src/Button.tsx
Labels: enhancement

#225 feat: add left icon to SelectField
  packages/ui/.loki/reference/chrome_minimal_Components_SelectField_With_Helper_Text.png
  packages/ui/.loki/reference/chrome_minimal_Components_SelectField_With_Icon_Left.png
  packages/ui/__stories__/SelectField.stories.tsx
  packages/ui/__tests__/Calendar/components/CalendarHeader.test.tsx
  packages/ui/__tests__/SelectField.test.tsx
  packages/ui/src/SelectField.module.scss
  packages/ui/src/SelectField.tsx
Labels: enhancement

#228 Feat: add 'closable' option to Dialog props
  packages/ui/src/Dialog.tsx
  packages/ui/src/Modal.tsx
Labels: enhancement
