Repository hazelcast/hive, pull requests merged in 2021-02, with the labels that each got.

#169 Feature/empty state
  packages/ui/.loki/reference/chrome_minimal_components_EmptyState_Horizontal.png
  packages/ui/.loki/reference/chrome_minimal_components_EmptyState_Horizontal_With_Action.png
  packages/ui/.loki/reference/chrome_minimal_components_EmptyState_Horizontal_With_Description.png
  packages/ui/.loki/reference/chrome_minimal_components_EmptyState_Horizontal_With_Description_And_Action.png
  packages/ui/.loki/reference/chrome_minimal_components_EmptyState_Horizontal_With_Description_And_Action_Long.png
  packages/ui/.loki/reference/chrome_minimal_components_EmptyState_Vertical.png
  packages/ui/.loki/reference/chrome_minimal_components_EmptyState_Vertical_Description_And_Action.png
  packages/ui/.loki/reference/chrome_minimal_components_EmptyState_Vertical_Large.png
  packages/ui/.loki/reference/chrome_minimal_components_EmptyState_Vertical_Large_With_Action.png
  packages/ui/.loki/reference/chrome_minimal_components_EmptyState_Vertical_Large_With_Description.png
  packages/ui/.loki/reference/chrome_minimal_components_EmptyState_Vertical_Large_With_Description_And_Action.png
  packages/ui/.loki/reference/chrome_minimal_components_EmptyState_Vertical_Large_With_Description_And_Action_Long.png
  packages/ui/.loki/reference/chrome_minimal_components_EmptyState_Vertical_With_Action.png
  packages/ui/.loki/reference/chrome_minimal_components_EmptyState_Vertical_With_Description.png
  packages/ui/.loki/reference/chrome_minimal_components_EmptyState_Vertical_With_Description_And_Action_Long.png
  packages/ui/__stories__/EmptyState.stories.tsx
  packages/ui/__tests__/EmptyState.test.tsx
  packages/ui/src/Button.tsx
  packages/ui/src/Dialog.tsx
  packages/ui/src/EmptyState.module.scss
  packages/ui/src/EmptyState.tsx
  packages/ui/src/Icon.tsx
  packages/ui/styles/constants/_sizes.scss
Labels: enhancement

#174 Copy SCSS from nested folders
  packages/ui/package.json
Labels: bug

#175 Fix build
  packages/ui/package.json
Labels: bug

#178 fix: react-use imports and remove use-deep-compare
  packages/ui/src/Alert.tsx
  packages/ui/src/Pagination.tsx
  packages/ui/src/Toast.tsx
  packages/ui/src/hooks/useDeepCompareMemo.ts
  packages/ui/src/hooks/useDeepEqual.ts
  packages/ui/src/hooks/useDimensions.ts
Labels: bug

#182 chore(ui): export slider component
  packages/ui/src/index.ts
Labels: UI

#184 Feat: add 'hideActions' prop to Modal
  package-lock.json
  packages/ui/.loki/reference/chrome_minimal_Components_Modal_With_Hidden_Modal_Actions.png
  packages/ui/__stories__/Modal.stories.tsx
  packages/ui/__tests__/Modal.test.tsx
  packages/ui/src/Modal.tsx
Labels: enhancement

#186 Fix react-table types augmentation
  package-lock.json
  packages/ui/@types/react-table.d.ts
  packages/ui/src/Table/Table.tsx
Labels: bug

#185 Feat: add isCreatable option to SelectField
  packages/ui/.loki/reference/chrome_minimal_Components_SelectField_Creatable.png
  packages/ui/__stories__/SelectField.stories.tsx
  packages/ui/__tests__/SelectField.test.tsx
  packages/ui/src/SelectField.tsx
Labels: enhancement
